apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    purpose: rs-demo
spec:
  replicas: 10
  selector:
    matchLabels:
      purspose: rs-demo
  template:
   metadata:
    labels:
      purpose: rs-demo
   spec:
    containers:
    - name: nginx
      image: nginx:trixie-perl
  