apiVersion: v1
kind: Pod
metadata: 
    name: resource_demo

spec:
  containers:
  - name: nginx
    image: nginx
    resource:
      requests:
       memory: "68Mi"
       cpu: "100m"
      limits:
       memory: "100Mi"
       cpu: "120m"